##  (C) Copyright 2014 Alvaro J. Genial (http://alva.ro)

language: python

branches:
  only:
    - master

install:
  - pip install django

script:
  - travis_wait python setup.py build
  - sudo python setup.py install
  - python tests/simple_template.py