##  (C) Copyright 2014 Alvaro J. Genial (http://alva.ro)

language: python

branches:
  only:
    - master

os:
  - osx
  - linux

before_install:
  - python --version
  - pip --version

install:
  - pip install django
  - travis_wait pip install synth

script:
  - sudo python setup.py install && python tests/simple_template.py
