##  (C) Copyright 2014 Alvaro J. Genial (http://alva.ro)

from django.template import Template, Context
from django.conf import settings
settings.configure()

c = Context({})

def test(s):
    print s, '=', Template("`" + s + "`").render(c)

test("{{ \"Joel is a slug\" | truncatechars:0 }}")
test("{{ \"Joel is a slug\" | truncatechars:1 }}")
test("{{ \"Joel is a slug\" | truncatechars:2 }}")
test("{{ \"Joel is a slug\" | truncatechars:3 }}")
test("{{ \"Joel is a slug\" | truncatechars:4 }}")
test("{{ \"Joel is a slug\" | truncatechars:5 }}")
test("{{ \"Joel is a slug\" | truncatechars:6 }}")
test("{{ \"Joel is a slug\" | truncatechars:7 }}")
test("{{ \"Joel is a slug\" | truncatechars:8 }}")
test("{{ \"Joel is a slug\" | truncatechars:9 }}")
test("{{ \"Joel is a slug\" | truncatechars:10 }}")
test("{{ \"Joel is a slug\" | truncatechars:11 }}")
test("{{ \"Joel is a slug\" | truncatechars:12 }}")
test("{{ \"Joel is a slug\" | truncatechars:13 }}")
test("{{ \"Joel is a slug\" | truncatechars:14 }}")
test("{{ \"Joel is a slug\" | truncatechars:15 }}")

test("{{ \"  Joel  is a  slug \" | truncatechars:0 }}")
test("{{ \"  Joel  is a  slug \" | truncatechars:1 }}")
test("{{ \"  Joel  is a  slug \" | truncatechars:2 }}")
test("{{ \"  Joel  is a  slug \" | truncatechars:3 }}")
test("{{ \"  Joel  is a  slug \" | truncatechars:4 }}")
test("{{ \"  Joel  is a  slug \" | truncatechars:5 }}")
test("{{ \"  Joel  is a  slug \" | truncatechars:6 }}")
test("{{ \"  Joel  is a  slug \" | truncatechars:7 }}")
test("{{ \"  Joel  is a  slug \" | truncatechars:8 }}")
test("{{ \"  Joel  is a  slug \" | truncatechars:9 }}")
test("{{ \"  Joel  is a  slug \" | truncatechars:10 }}")
test("{{ \"  Joel  is a  slug \" | truncatechars:11 }}")
test("{{ \"  Joel  is a  slug \" | truncatechars:12 }}")
test("{{ \"  Joel  is a  slug \" | truncatechars:13 }}")
test("{{ \"  Joel  is a  slug \" | truncatechars:14 }}")
test("{{ \"  Joel  is a  slug \" | truncatechars:15 }}")

'''
test("{{ \"Joel <a href='#'>is <i>a</i> slug</a>\" | truncatechars_html:0 }}")
test("{{ \"Joel <a href='#'>is <i>a</i> slug</a>\" | truncatechars_html:1 }}")
test("{{ \"Joel <a href='#'>is <i>a</i> slug</a>\" | truncatechars_html:2 }}")
test("{{ \"Joel <a href='#'>is <i>a</i> slug</a>\" | truncatechars_html:3 }}")
test("{{ \"Joel <a href='#'>is <i>a</i> slug</a>\" | truncatechars_html:4 }}")
test("{{ \"Joel <a href='#'>is <i>a</i> slug</a>\" | truncatechars_html:5 }}")
test("{{ \"Joel <a href='#'>is <i>a</i> slug</a>\" | truncatechars_html:6 }}")
test("{{ \"Joel <a href='#'>is <i>a</i> slug</a>\" | truncatechars_html:7 }}")
test("{{ \"Joel <a href='#'>is <i>a</i> slug</a>\" | truncatechars_html:8 }}")
test("{{ \"Joel <a href='#'>is <i>a</i> slug</a>\" | truncatechars_html:9 }}")
test("{{ \"Joel <a href='#'>is <i>a</i> slug</a>\" | truncatechars_html:10 }}")
test("{{ \"Joel <a href='#'>is <i>a</i> slug</a>\" | truncatechars_html:11 }}")
test("{{ \"Joel <a href='#'>is <i>a</i> slug</a>\" | truncatechars_html:12 }}")
test("{{ \"Joel <a href='#'>is <i>a</i> slug</a>\" | truncatechars_html:13 }}")
test("{{ \"Joel <a href='#'>is <i>a</i> slug</a>\" | truncatechars_html:14 }}")
test("{{ \"Joel <a href='#'>is <i>a</i> slug</a>\" | truncatechars_html:15 }}")

test("{{ \"Joel <a href='#'>is <i>a</i> slug\" | truncatechars_html:0 }}")
test("{{ \"Joel <a href='#'>is <i>a</i> slug\" | truncatechars_html:1 }}")
test("{{ \"Joel <a href='#'>is <i>a</i> slug\" | truncatechars_html:2 }}")
test("{{ \"Joel <a href='#'>is <i>a</i> slug\" | truncatechars_html:3 }}")
test("{{ \"Joel <a href='#'>is <i>a</i> slug\" | truncatechars_html:4 }}")
test("{{ \"Joel <a href='#'>is <i>a</i> slug\" | truncatechars_html:5 }}")
test("{{ \"Joel <a href='#'>is <i>a</i> slug\" | truncatechars_html:6 }}")
test("{{ \"Joel <a href='#'>is <i>a</i> slug\" | truncatechars_html:7 }}")
test("{{ \"Joel <a href='#'>is <i>a</i> slug\" | truncatechars_html:8 }}")
test("{{ \"Joel <a href='#'>is <i>a</i> slug\" | truncatechars_html:9 }}")
test("{{ \"Joel <a href='#'>is <i>a</i> slug\" | truncatechars_html:10 }}")
test("{{ \"Joel <a href='#'>is <i>a</i> slug\" | truncatechars_html:11 }}")
test("{{ \"Joel <a href='#'>is <i>a</i> slug\" | truncatechars_html:12 }}")
test("{{ \"Joel <a href='#'>is <i>a</i> slug\" | truncatechars_html:13 }}")
test("{{ \"Joel <a href='#'>is <i>a</i> slug\" | truncatechars_html:14 }}")
test("{{ \"Joel <a href='#'>is <i>a</i> slug\" | truncatechars_html:15 }}")
'''


test("{{ \"Joel is a slug\" | truncatewords:-2 }}")
test("{{ \"Joel is a slug\" | truncatewords:-1 }}")
test("{{ \"Joel is a slug\" | truncatewords:0 }}")
test("{{ \"Joel is a slug\" | truncatewords:1 }}")
test("{{ \"Joel is a slug\" | truncatewords:2 }}")
test("{{ \"Joel is a slug\" | truncatewords:3 }}")
test("{{ \"Joel is a slug\" | truncatewords:4 }}")
test("{{ \"Joel is a slug\" | truncatewords:5 }}")

test("{{ \"  Joel  is a  slug \" | truncatewords:0 }}")
test("{{ \"  Joel  is a  slug \" | truncatewords:1 }}")
test("{{ \"  Joel  is a  slug \" | truncatewords:2 }}")
test("{{ \"  Joel  is a  slug \" | truncatewords:3 }}")
test("{{ \"  Joel  is a  slug \" | truncatewords:4 }}")
test("{{ \"  Joel  is a  slug \" | truncatewords:5 }}")

test("{{ \"<p>Joel is a slug</p>\" | truncatewords_html:0 }}")
test("{{ \"<p>Joel is a slug</p>\" | truncatewords_html:1 }}")
test("{{ \"<p>Joel is a slug</p>\" | truncatewords_html:2 }}")
test("{{ \"<p>Joel is a slug</p>\" | truncatewords_html:3 }}")
test("{{ \"<p>Joel is a slug</p>\" | truncatewords_html:4 }}")
test("{{ \"<p>Joel is a slug</p>\" | truncatewords_html:5 }}")

test("{{ \"<p>Joel is a slug\" | truncatewords_html:0 }}")
test("{{ \"<p>Joel is a slug\" | truncatewords_html:1 }}")
test("{{ \"<p>Joel is a slug\" | truncatewords_html:2 }}")
test("{{ \"<p>Joel is a slug\" | truncatewords_html:3 }}")
test("{{ \"<p>Joel is a slug\" | truncatewords_html:4 }}")
test("{{ \"<p>Joel is a slug\" | truncatewords_html:5 }}")

test("{{ \"Joel <a href='#'>is <i>a</i> slug</a>\" | truncatewords_html:0 }}")
test("{{ \"Joel <a href='#'>is <i>a</i> slug</a>\" | truncatewords_html:1 }}")
test("{{ \"Joel <a href='#'>is <i>a</i> slug</a>\" | truncatewords_html:2 }}")
test("{{ \"Joel <a href='#'>is <i>a</i> slug</a>\" | truncatewords_html:3 }}")
test("{{ \"Joel <a href='#'>is <i>a</i> slug</a>\" | truncatewords_html:4 }}")
test("{{ \"Joel <a href='#'>is <i>a</i> slug</a>\" | truncatewords_html:5 }}")

test("{{ \"Joel <a href='#'>is <i>a</i> slug\" | truncatewords_html:0 }}")
test("{{ \"Joel <a href='#'>is <i>a</i> slug\" | truncatewords_html:1 }}")
test("{{ \"Joel <a href='#'>is <i>a</i> slug\" | truncatewords_html:2 }}")
test("{{ \"Joel <a href='#'>is <i>a</i> slug\" | truncatewords_html:3 }}")
test("{{ \"Joel <a href='#'>is <i>a</i> slug\" | truncatewords_html:4 }}")
test("{{ \"Joel <a href='#'>is <i>a</i> slug\" | truncatewords_html:5 }}")

test("{{ \"  Joel <a href='#'>  is  <i>  a  </i>  slug  </a>  \" | truncatewords_html:0 }}")
test("{{ \"  Joel <a href='#'>  is  <i>  a  </i>  slug  </a>  \" | truncatewords_html:1 }}")
test("{{ \"  Joel <a href='#'>  is  <i>  a  </i>  slug  </a>  \" | truncatewords_html:2 }}")
test("{{ \"  Joel <a href='#'>  is  <i>  a  </i>  slug  </a>  \" | truncatewords_html:3 }}")
test("{{ \"  Joel <a href='#'>  is  <i>  a  </i>  slug  </a>  \" | truncatewords_html:4 }}")
test("{{ \"  Joel <a href='#'>  is  <i>  a  </i>  slug  </a>  \" | truncatewords_html:5 }}")

test("{{ \"  Joel <a href='#'>  is  <i>  a  </i>  slug  \" | truncatewords_html:0 }}")
test("{{ \"  Joel <a href='#'>  is  <i>  a  </i>  slug  \" | truncatewords_html:1 }}")
test("{{ \"  Joel <a href='#'>  is  <i>  a  </i>  slug  \" | truncatewords_html:2 }}")
test("{{ \"  Joel <a href='#'>  is  <i>  a  </i>  slug  \" | truncatewords_html:3 }}")
test("{{ \"  Joel <a href='#'>  is  <i>  a  </i>  slug  \" | truncatewords_html:4 }}")
test("{{ \"  Joel <a href='#'>  is  <i>  a  </i>  slug  \" | truncatewords_html:5 }}")

